version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      # Atualize o host, se necessário, para o IP ou nome do servidor do seu banco de dados existente
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork: